# Generated by Django 2.1.3 on 2018-12-28 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 16, 41, 19, 694671, tzinfo=utc), verbose_name='date published'),
        ),
    ]
